export const data = [
    {imageUrl: "/images/angular.png", alt: "angular"},
    {imageUrl: "/images/bootstrap.png", alt: "bootstrap"},
    {imageUrl: "/images/css.png", alt: "css"},
    {imageUrl: "/images/html.png", alt: "html"},
    {imageUrl: "/images/js.png", alt: "js"},
    {imageUrl: "/images/php.png", alt: "php"},
    {imageUrl: "/images/react.png", alt: "react"},
    {imageUrl: "/images/solid.png", alt: "solid"},
    {imageUrl: "/images/tailwind.png", alt: "tailwind"},
    {imageUrl: "/images/vue.png", alt: "vue"},
    {imageUrl: "/images/angular.png", alt: "angular"},
    {imageUrl: "/images/bootstrap.png", alt: "bootstrap"},
    {imageUrl: "/images/css.png", alt: "css"},
    {imageUrl: "/images/html.png", alt: "html"},
    {imageUrl: "/images/js.png", alt: "js"},
    {imageUrl: "/images/php.png", alt: "php"},
    {imageUrl: "/images/react.png", alt: "react"},
    {imageUrl: "/images/solid.png", alt: "solid"},
    {imageUrl: "/images/tailwind.png", alt: "tailwind"},
    {imageUrl: "/images/vue.png", alt: "vue"},
]